GET http://localhost:3000

###

GET http://localhost:3000/books

###

POST http://localhost:3000/books
Content-Type: application/json

{
  "title": "Corporate",
  "description": "Data scientiste",
  "image": "https://images-platform.99static.com//g8_sYzJXM7EFtF-Ri_bCqEsJarQ=/fit-in/590x590/projects-files/44/4474/447491/a076f76d-8ffe-4daa-8b74-cc71d3902ee4.jpg",
  "price": 9.9,
  "author": "Alien test",
  "stars": 9
}